(TeX-add-style-hook
 "chap3"
 (lambda ()
   (LaTeX-add-index-entries
    "gnu"
    "gnu!diet"
    "gnu!diet!wet season"
    "gnu!diet!dry season"
    "gnu!predators"
    "gnu!predators!crocodiles"
    "gnu!predators!hyenas"
    "gnu!predators!lions"
    "rhinodon"
    "rhinodont"
    "rhinoceros"
    "rhinoceros horn"
    "rhinocerite"
    "rhinestone"
    "Rhineland"
    "Rhinegrave"
    "Rhine berry"
    "rhea"
    "rat"
    "raccoon"
    "Queensland viper"
    "quail"
    "quagga"
    "puffin"
    "pterodactyl"
    "pronghorn (\\bioname{Antilocapra americana})"
    "peccary"
    "panther"
    "panda"
    "opossum"
    "okapi"
    "octopus"
    "ocelot (\\bioname{Leopardus pardalis})"
    "nilgai"
    "Neanderthal"
    "nautilus"
    "narwhal"
    "muskrat"
    "musk ox"
    "moose (\\bioname{Alces alces})"
    "mastodon"
    "mastiff"
    "marmot (\\bioname{Marmota marmota})"
    "margay (\\bioname{Leopardus wiedii})"
    "manatee (\\bioname{Trichechus inunguis})"
    "mammoth"
    "lynx (\\bioname{Lynx canadensis})"
    "llama (\\bioname{Lama glama})"
    "lion"
    "leopard"
    "lemur"
    "lemming"
    "kudu"
    "kangaroo"
    "koala"
    "jerboa"
    "jaguar (\\bioname{Panthera onca})"
    "jackrabbit"
    "jackass"
    "jackal"
    "impala"
    "ibex"
    "hyena"
    "hippopotamus"
    "hartebeest"
    "giraffe"
    "gila monster"
    "gecko"
    "gazelle"
    "fox"
    "ferret"
    "elk (\\bioname{Cervus canadensis})"
    "elephant"
    "deer"
    "crocodile"
    "coyote"
    "cougar (\\bioname{Puma concolor})"
    "cheetah"
    "caribou"
    "bongo (\\bioname{Tragelaphus eurycerus})"
    "bobcat (\\bioname{Lynx rufus})"
    "bison"
    "beaver"
    "azymous (unleavened)"
    "aoudad"
    "antelope"
    "addax"
    "aardwolf"
    "aardvark"
    "Alces alces@\\bioname{Alces alces}"
    "Antilocapra americana@\\bioname{Antilocapra americana}"
    "Cervus canadensis@\\bioname{Cervus canadensis}"
    "Lama glama@\\bioname{Lama glama}"
    "Lynx canadensis@\\bioname{Lynx canadensis}"
    "Marmota marmota@\\bioname{Marmota marmota}"
    "Panthera onca@\\bioname{Panthera onca}"
    "Tragelaphus eurycerus@\\bioname{Tragelaphus eurycerus}"))
 :latex)

